name: mlops
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - pyyaml
  - scikit-learn
  - joblib
  - pytest
  - pytest-cov
  - matplotlib
  - seaborn
  - requests
  - ipykernel
  - jupyter
  - python-dotenv
